---
- hosts: all
  become: yes
  tasks:
  - name: Add Dana
    user:
      name: dana
      comment: Dana
      group: wheel
      # Created with: 
      # openssl passwd -salt <salt here> -1 <password here>
      password: $1$hskjdfh$j7D.av2Q7/j7E86eP.NaZ.
